#ifndef _APP_H_
#define _APP_H_

#include <stdio.h>
#include <string.h>
#include <iostream>
#include <vector>
#include <sstream>
#include <assert.h>

// ignore the warning here, this file is generated by sgxedger8r during build process
#include "Enclave_u.h"
// asserting we are pointing to the definitions that are part of our instrumented SDK 
#include "/opt/intel/sgxsdk/include/sgx_urts.h"


#include "/opt/intel/sgxsdk/include/sgx_error.h"       // sgx_status_t 
#include "/opt/intel/sgxsdk/include/sgx_eid.h"     // sgx_enclave_id_t 
#include "/opt/intel/sgxsdk/include/sgx_uae_epid.h" // quoting process

#ifndef TRUE
# define TRUE 1
#endif

#ifndef FALSE
# define FALSE 0
#endif

# define ENCLAVE_FILENAME "enclave.signed.so"

extern sgx_enclave_id_t global_eid;    // global enclave id

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
}   
#endif
#endif